<?php

/**
 * @file
 * Convivial Profiler module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function convivial_profiler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.convivial_profiler':
      $output = '';
      $output .= '<h3>' . t('Convivial Profiler') . '</h3>';
      $output .= '<p>' . t('Provides ability for personalization and visitor data collection') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function convivial_profiler_page_attachments(array &$attachments) {
  $config = \Drupal::config('convivial_profiler.settings');
  if (empty($site = $config->get('site_id')) || empty($license_key = $config->get('license_key'))) {
    return;
  }
  $attachments['#attached']['library'][] = 'convivial_profiler/init';
  $attachments['#attached']['drupalSettings']['convivialProfiler'] = [
    'site' => $site,
    'license_key' => $license_key,
    'client_cleanup' => $config->get('client_cleanup'),
    'event_tracking' => $config->get('event_tracking'),
    'config' => [
      'profilers' => $config->get('profilers') ?? (object) [],
    ],
  ];
}
