convivial_profiler.settings:
  type: config_object
  label: 'Convivial Profiler settings'
  mapping:
    site_id:
      type: string
      label: 'Site ID'
    license_key:
      type: string
      label: 'License key'
    client_cleanup:
      type: boolean
      label: 'Client cleanup'
    event_tracking:
      type: boolean
      label: 'Event tracking'
    profilers:
      type: sequence
      label: 'Profilers'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
          label:
            type: string
          weight:
            type: integer
          status:
            type: boolean
          description:
            type: string
          deferred:
            type: boolean
          sources:
            type: sequence
            label: 'Sources'
            sequence:
              type: mapping
              label: 'Source'
              mapping:
                type:
                  type: string
                key:
                  type: string
                name:
                  type: string
                resource_url:
                  type: string
                attribute_name:
                  type: string
                param:
                  type: string
                part:
                  type: string
          processors:
            type: sequence
            label: 'Processors'
            sequence:
              type: mapping
              label: 'Processor'
              mapping:
                type:
                  type: string
                storage_key:
                  type: string
                storage_value:
                  type: string
                ttl:
                  type: integer
                normalize:
                  type: boolean
                search_path:
                  type: string
                query_param:
                  type: string
                exclude_param:
                  type: string
                size:
                  type: integer
                track:
                  type: boolean
                log:
                  type: boolean
                default_value:
                  type: string
                fallback_value:
                  type: string
                mappings:
                  type: sequence
                  sequence:
                    type: string
                    label: 'Mapping'
          destinations:
            type: sequence
            label: 'Destinations'
            sequence:
              type: mapping
              label: 'Destination'
              mapping:
                type:
                  type: string
                target_key:
                  type: string
                target_value:
                  type: string
                remove_empty:
                  type: boolean
                dimension_key:
                  type: string
                storage_key:
                  type: string
                storage_keys:
                  type: sequence
                  label: 'Storage keys'
                  sequence:
                    type: string
                    label: 'Storage key'
                default_value:
                  type: string
                stringify:
                  type: boolean
                static_values:
                  type: sequence
                  label: 'Static Values'
                  sequence:
                    type: string
                    label: 'Static Value'
                threshold_number:
                  type: integer
                category:
                  type: string
                action:
                  type: string
                normalize:
                  type: boolean
                storage_value:
                  type: string
                form_selector:
                  type: string
                fields_selector:
                  type: sequence
                  label: 'Fields Selector'
                  sequence:
                    type: string
                    label: 'Field selector'
                field_name:
                  type: string
                event_action:
                  type: string
                event_category:
                  type: string
                normal_start:
                  type: string
                normal_end:
                  type: string
                normal_offset:
                  type: string
                daylight_saving_start:
                  type: string
                daylight_saving_end:
                  type: string
                daylight_saving_offset:
                  type: string
                office_times:
                  type: sequence
                  label: 'Office times'
                  sequence:
                    type: mapping
                    label: 'Office time'
                    mapping:
                      day:
                        type: integer
                      start:
                        type: integer
                      close:
                        type: integer
                ranges:
                  type: sequence
                  label: 'Ranges'
                  sequence:
                    type: mapping
                    label: 'Range'
                    mapping:
                      key:
                        type: string
                      min:
                        type: integer
                      max:
                        type: integer
                target_location:
                  type: mapping
                  label: 'Target location'
                  mapping:
                    localstorage:
                      type: string
                    cookie:
                      type: string
                storage_source:
                  type: mapping
                  label: 'Storage source'
                  mapping:
                    localstorage:
                      type: string
                    cookie:
                      type: string
                flag_prefix:
                  type: string
                flag_suffix:
                  type: string
    visibility:
      type: sequence
      label: 'Visibility conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility condition'
